"""Telegram bot — sends rich job notifications with inline buttons.

Free, inline buttons, PDF support, no char limit.
Uses HTML parse mode for clean formatting.
"""

import logging
from html import escape
from pathlib import Path

from telegram import Bot, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.constants import ParseMode

from personal_assistant.config import settings
from personal_assistant.db.models import Job, JobStatus
from personal_assistant.db.queries import update_job_status

logger = logging.getLogger(__name__)

HTML = ParseMode.HTML

# In-memory store: job_id → list of Telegram message_ids for the apply plan
_plan_message_ids: dict[int, list[int]] = {}


def _bot() -> Bot:
    return Bot(token=settings.telegram_bot_token)


def _e(text: str | None) -> str:
    """HTML-escape user content."""
    return escape(text or "")


# ── Send helpers ──────────────────────────────────────────────────────────────

async def send_message(text: str, parse_mode: str | None = HTML) -> None:
    """Send a message to the configured chat."""
    bot = _bot()
    await bot.send_message(
        chat_id=settings.telegram_chat_id,
        text=text,
        parse_mode=parse_mode,
    )


async def send_document(file_path: str, caption: str = "") -> int | None:
    """Send a file (e.g. PDF) to the configured chat. Returns message_id."""
    bot = _bot()
    path = Path(file_path)
    if not path.exists():
        logger.error("File not found: %s", file_path)
        return None
    with open(path, "rb") as f:
        m = await bot.send_document(
            chat_id=settings.telegram_chat_id,
            document=f,
            filename=path.name,
            caption=caption[:1024] if caption else None,
            parse_mode=HTML,
        )
        return m.message_id


# ── Job notification ──────────────────────────────────────────────────────────

def _is_llm_summary(summary: str | None) -> bool:
    """True if the summary was generated by the LLM (not auto-scored keywords)."""
    if not summary:
        return False
    auto_prefixes = ("Auto-scored", "Strong keyword match", "Keyword score")
    return not summary.startswith(auto_prefixes)


def _format_job_message(job: Job) -> str:
    """Build an HTML-formatted job card."""
    # Salary
    if job.salary_min and job.salary_max:
        salary = f"${job.salary_min // 1000}K\u2013${job.salary_max // 1000}K CAD"
    elif job.salary_text:
        salary = _e(job.salary_text[:60])
    else:
        salary = "<i>Not listed</i>"

    remote = "Remote" if job.is_remote else "On-site / Hybrid"
    priority = " \u2b50" if job.is_priority_industry else ""

    if job.is_easy_apply:
        apply_method = "\u2705 <b>Easy Apply</b> \u2014 auto-submits on approve"
    else:
        apply_method = "External / Manual application"

    parts = [
        f"<b>JOB #{job.id}{priority}  \u2502  Score: {job.relevance_score}/100</b>",
        "",
        f"<b>{_e(job.title)}</b>",
        f"{_e(job.company)}",
        f"<i>{_e(job.location or 'N/A')}  \u2022  {remote}</i>",
        "",
        f"\u2022 <b>Salary:</b> {salary}",
        f"\u2022 <b>Apply:</b> {apply_method}",
    ]

    # Score analysis (always shown — renamed from "Summary")
    if job.summary:
        parts += ["", f"<b>Score Analysis</b>", f"<i>{_e(job.summary)}</i>"]

    # Only show description preview if it's an LLM-analyzed job
    # Otherwise just link to LinkedIn
    if _is_llm_summary(job.summary):
        desc = _e((job.description or "").strip())
        if len(desc) > 800:
            desc = desc[:800] + "..."
        if desc:
            parts += ["", f"<b>Description</b>", f"<blockquote>{desc}</blockquote>"]

    if job.job_url:
        parts += ["", f'<a href="{_e(job.job_url)}">View on LinkedIn</a>']

    return "\n".join(parts)


def _job_keyboard(job: Job) -> InlineKeyboardMarkup:
    """Inline buttons: Interested / Skip."""
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("\u2705 Interested", callback_data=f"apply:{job.id}"),
            InlineKeyboardButton("\u274c Skip", callback_data=f"skip:{job.id}"),
        ],
    ])


async def send_job_notification(job: Job) -> bool:
    """Send a Telegram message with job details + inline buttons."""
    bot = _bot()
    text = _format_job_message(job)
    keyboard = _job_keyboard(job)

    try:
        await bot.send_message(
            chat_id=settings.telegram_chat_id,
            text=text,
            parse_mode=HTML,
            reply_markup=keyboard,
        )
        update_job_status(job.id, JobStatus.NOTIFIED)
        logger.info("Telegram notification sent for job %d", job.id)
        return True
    except Exception as e:
        logger.error("Telegram notification failed for job %d: %s", job.id, e)
        return False


async def send_batch_notifications(jobs: list[Job]) -> int:
    """Send Telegram notifications for multiple jobs. Returns count sent."""
    sent = 0
    for job in jobs:
        if await send_job_notification(job):
            sent += 1
    logger.info("Sent %d/%d Telegram notifications", sent, len(jobs))
    return sent


# ── Apply plan notification ───────────────────────────────────────────────────

async def send_apply_plan(
    job: Job,
    pdf_path: str | None,
    cv_changes_summary: str | None,
    contacts_info: list[dict],
    outreach_messages: dict[str, str],
    easy_apply_done: bool,
) -> None:
    """Send the full apply plan with CV, outreach messages, and action buttons."""
    bot = _bot()
    chat_id = settings.telegram_chat_id
    sent_ids: list[int] = []

    # ── 1. Header + how to apply ──────────────────────────────────────────────
    parts = [
        f"<b>Apply Plan \u2014 Job #{job.id}</b>",
        f"<b>{_e(job.title)}</b> @ {_e(job.company)}",
        "",
    ]

    apply_channels = []
    if easy_apply_done:
        parts.append("\u2705 <b>Easy Apply submitted!</b>")
        apply_channels.append("easy_apply")
    elif job.is_easy_apply:
        parts.append("\u2022 <b>Easy Apply</b> \u2014 ready to auto-submit")
        apply_channels.append("easy_apply")

    if job.job_url:
        parts.append(f'\u2022 <a href="{_e(job.job_url)}">Apply on LinkedIn</a>')
        apply_channels.append("linkedin")

    parts.append("")
    m = await bot.send_message(chat_id=chat_id, text="\n".join(parts), parse_mode=HTML)
    sent_ids.append(m.message_id)

    # ── 2. CV + changes summary ───────────────────────────────────────────────
    if pdf_path:
        caption = f"Tailored CV for <b>{_e(job.title)}</b> @ {_e(job.company)}"
        if cv_changes_summary:
            caption += f"\n\n<i>{_e(cv_changes_summary)}</i>"
        doc_id = await send_document(pdf_path, caption=caption[:1024])
        if doc_id:
            sent_ids.append(doc_id)

    # ── 3. Outreach messages (each in a collapsible blockquote) ───────────────
    if contacts_info:
        for i, c in enumerate(contacts_info, 1):
            name = _e(c.get("name", ""))
            title_text = _e(c.get("title", ""))
            channel = _e(c.get("channel", "LinkedIn"))

            msg_parts = [f"<b>Contact {i}: {name}</b>"]
            if title_text:
                msg_parts.append(f"<i>{title_text}</i>")
            if c.get("linkedin_url"):
                msg_parts.append(f'<a href="{_e(c["linkedin_url"])}">LinkedIn profile</a>')

            msg_parts.append(f"\u2022 Channel: <b>{channel}</b>")

            # Show drafted message in expandable blockquote
            cid = str(c.get("id", i))
            ch = c.get("channel", "LinkedIn").lower()
            msg_key = f"{cid}_{ch}"
            drafted = outreach_messages.get(msg_key, outreach_messages.get(cid, c.get("message_preview", "")))
            if drafted:
                msg_parts.append("")
                msg_parts.append(f"<blockquote expandable>{_e(drafted)}</blockquote>")

            cm = await bot.send_message(
                chat_id=chat_id,
                text="\n".join(msg_parts),
                parse_mode=HTML,
            )
            sent_ids.append(cm.message_id)

    # ── 4. Action buttons ─────────────────────────────────────────────────────
    buttons = []

    # Apply buttons
    if not easy_apply_done:
        if len(apply_channels) > 0:
            buttons.append([
                InlineKeyboardButton(
                    "\U0001f680 Apply to All",
                    callback_data=f"applyall:{job.id}",
                ),
            ])
        if job.is_easy_apply and not easy_apply_done:
            buttons.append([
                InlineKeyboardButton(
                    "\u2705 Easy Apply Only",
                    callback_data=f"easyonly:{job.id}",
                ),
            ])

    # Outreach buttons
    if contacts_info:
        buttons.append([
            InlineKeyboardButton(
                "\U0001f4e8 Send All Outreach",
                callback_data=f"sendall:{job.id}",
            ),
        ])

    # Tweak / Done buttons
    buttons.append([
        InlineKeyboardButton("\u270f\ufe0f Tweak CV", callback_data=f"tweakcv:{job.id}"),
        InlineKeyboardButton("\u270f\ufe0f Tweak Messages", callback_data=f"tweakmsg:{job.id}"),
    ])
    buttons.append([
        InlineKeyboardButton("\u2705 Applied", callback_data=f"done:{job.id}"),
    ])

    am = await bot.send_message(
        chat_id=chat_id,
        text="<b>What would you like to do?</b>",
        parse_mode=HTML,
        reply_markup=InlineKeyboardMarkup(buttons),
    )
    sent_ids.append(am.message_id)

    # Store message IDs so they can be deleted when user presses "Applied"
    _plan_message_ids[job.id] = sent_ids
